//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_view
    {
        public string Client_Customer_Number { get; set; }
        public string Client_Name { get; set; }
        public string Client_Account_Number { get; set; }
        public string Client_PortFolio_ID { get; set; }
        public string Client_Sector_ID { get; set; }
        public long Client_ID { get; set; }
        public string RM_Email { get; set; }
        public string RM_Name { get; set; }
        public long Expr1 { get; set; }
        public string Status { get; set; }
    }
}
