//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_details
    {
        public string Client_Customer_Number { get; set; }
        public string Client_Name { get; set; }
        public string Client_Account_Number { get; set; }
        public Nullable<long> RM_ID { get; set; }
        public string Client_PortFolio_ID { get; set; }
        public string Client_Sector_ID { get; set; }
        public long Client_ID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> inserted_date { get; set; }
        public Nullable<long> inserted_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<long> modified_by { get; set; }
        public string Client_Branch_Code { get; set; }
    }
}
