//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public currency()
        {
            this.instructions = new HashSet<instruction>();
        }
    
        public long currency_id { get; set; }
        public string currency_name { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<long> rate_approved_by { get; set; }
        public Nullable<System.DateTime> rate_approved_date { get; set; }
        public Nullable<long> rate_updated_by { get; set; }
        public Nullable<System.DateTime> rate_updated_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<instruction> instructions { get; set; }
    }
}
