//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_status_view
    {
        public string user_type_no { get; set; }
        public string user_type { get; set; }
        public string document_status { get; set; }
        public Nullable<int> document_status_stage { get; set; }
        public string document_status_action { get; set; }
        public long document_status_id { get; set; }
        public Nullable<int> is_rework { get; set; }
        public string unit { get; set; }
    }
}
