//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ds_external_email
    {
        public Nullable<System.DateTime> email_date { get; set; }
        public string email_body { get; set; }
        public string email_from { get; set; }
        public string email_to { get; set; }
        public string email_cc { get; set; }
        public string email_bcc { get; set; }
        public Nullable<int> sent { get; set; }
        public Nullable<int> attempts { get; set; }
        public long email_id { get; set; }
        public string email_subject { get; set; }
        public Nullable<System.DateTime> sent_date { get; set; }
        public string email_attachment_path { get; set; }
    }
}
