//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_notification_parameters
    {
        public int instruction_status { get; set; }
        public int minutes_to_cut_off { get; set; }
        public Nullable<System.DateTime> email_last_notification_time { get; set; }
        public Nullable<int> email_to_user_type { get; set; }
        public string email_to_user_email { get; set; }
        public long email_notification_parameters_id { get; set; }
        public Nullable<int> active { get; set; }
        public string email_notification_type { get; set; }
        public string email_notification_time { get; set; }
    }
}
