//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class inprogress_by_stage_and_instruction_type
    {
        public Nullable<int> number_of_instructions { get; set; }
        public string user_type_no { get; set; }
        public string user_type { get; set; }
        public long instruction_type_id { get; set; }
        public string instruction_type { get; set; }
    }
}
