//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class instructions_view
    {
        public Nullable<double> amount { get; set; }
        public string comments { get; set; }
        public string reference { get; set; }
        public string file_name { get; set; }
        public long instruction_id { get; set; }
        public long instruction_type_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<long> client_id { get; set; }
        public string file_type { get; set; }
        public string instruction_type { get; set; }
        public string Client_Name { get; set; }
        public string Client_Account_Number { get; set; }
        public string Client_Customer_Number { get; set; }
        public Nullable<System.DateTime> allocated_date { get; set; }
        public string processor_comments { get; set; }
        public string ftrob_comments { get; set; }
        public string ftroa_comments { get; set; }
        public string account_no { get; set; }
        public Nullable<long> currency_id { get; set; }
        public Nullable<System.DateTime> ftro_proccessed_date { get; set; }
        public Nullable<System.DateTime> ftro_approved_date { get; set; }
        public string branch_proccessed_date { get; set; }
        public Nullable<System.DateTime> processor_proccessed_date { get; set; }
        public Nullable<long> ftro_proccessed_by { get; set; }
        public Nullable<long> ftro_approved_by { get; set; }
        public Nullable<long> branch_proccessed_by { get; set; }
        public Nullable<long> processor_proccessed_by { get; set; }
        public string branch_user { get; set; }
        public string ftroa_user { get; set; }
        public string ftrob_user { get; set; }
        public string processor_user { get; set; }
        public Nullable<int> instruction_status { get; set; }
        public string document_status_name { get; set; }
        public Nullable<long> branch_approved_by { get; set; }
        public Nullable<long> system_user_id { get; set; }
        public string branch_approved_by_user { get; set; }
        public string branch_approved_date { get; set; }
        public Nullable<long> processor_approved_by { get; set; }
        public Nullable<System.DateTime> processor_approved_date { get; set; }
        public Nullable<long> document_status_id { get; set; }
        public string allocated_to_name { get; set; }
        public Nullable<long> allocated_to { get; set; }
        public string processor_approved_by_name { get; set; }
        public Nullable<long> locked_by { get; set; }
        public string locked_date { get; set; }
        public string locked_by_name { get; set; }
        public string currency_name { get; set; }
        public Nullable<int> inserted_by { get; set; }
        public string rm_comments { get; set; }
        public string ft_reference { get; set; }
        public Nullable<long> rm_id { get; set; }
        public Nullable<long> branch_id { get; set; }
        public Nullable<long> rm_proccessed_by { get; set; }
        public Nullable<System.DateTime> rm_proccessed_date { get; set; }
        public Nullable<System.DateTime> inserted_date { get; set; }
        public Nullable<System.DateTime> processor_allocated_date { get; set; }
        public Nullable<long> processor_allocated_by { get; set; }
        public Nullable<System.DateTime> ftro_allocated_date { get; set; }
        public Nullable<long> ftro_allocated_by { get; set; }
        public Nullable<int> exception { get; set; }
        public Nullable<int> foward_back_to_after_reversal { get; set; }
        public Nullable<long> branch_manual_approved_by { get; set; }
        public Nullable<System.DateTime> branch_manual_approved_date { get; set; }
        public string related_reference { get; set; }
        public Nullable<int> document_status_stage { get; set; }
        public string status_calculation { get; set; }
        public string RM_Name { get; set; }
        public string processing_department { get; set; }
        public string processor_approved_date_name { get; set; }
        public Nullable<int> total_processing_time { get; set; }
        public string branch_name { get; set; }
        public Nullable<int> priority { get; set; }
        public string instruction_code { get; set; }
        public Nullable<int> picked_by { get; set; }
        public Nullable<System.DateTime> picked_date { get; set; }
        public Nullable<int> is_document_held { get; set; }
        public Nullable<long> prmo2_proccessed_by { get; set; }
        public Nullable<System.DateTime> prmo2_proccessed_date { get; set; }
        public Nullable<long> prmu_tl_proccessed_by { get; set; }
        public Nullable<System.DateTime> prmu_tl_proccessed_date { get; set; }
        public Nullable<long> prmu_manager_proccessed_by { get; set; }
        public Nullable<System.DateTime> prmu_manager_proccessed_date { get; set; }
        public string call_back_comments { get; set; }
        public Nullable<long> doc_comments_id { get; set; }
        public string doc_comments { get; set; }
        public string prmo2_comments { get; set; }
        public string call_back_no { get; set; }
        public Nullable<int> is_referral { get; set; }
        public Nullable<int> must_comment { get; set; }
        public string delivery_date { get; set; }
        public Nullable<int> processed_at_branch { get; set; }
        public Nullable<long> referred_to { get; set; }
        public Nullable<System.DateTime> referred_to_date { get; set; }
        public Nullable<long> referred_to_by { get; set; }
        public string cutt_off_time { get; set; }
        public Nullable<int> prmo1_popup_alert_status { get; set; }
        public Nullable<System.DateTime> prmo1_popup_alert_time { get; set; }
        public Nullable<int> processor_popup_alert_status { get; set; }
        public Nullable<System.DateTime> processor_popup_alert_time { get; set; }
        public Nullable<int> processing_day { get; set; }
        public Nullable<int> manual_priority { get; set; }
        public string picked_by_name { get; set; }
        public string prmo2_proccessed_by_name { get; set; }
        public string prmu_tl_proccessed_by_name { get; set; }
        public string prmu_manager_proccessed_by_name { get; set; }
        public Nullable<int> is_archived { get; set; }
        public Nullable<int> doc_is_amust { get; set; }
        public string unit { get; set; }
        public string stage { get; set; }
        public Nullable<int> is_rework { get; set; }
        public Nullable<int> branch_recall_allowed { get; set; }
        public string validation_manager { get; set; }
        public Nullable<int> cross_currency { get; set; }
        public Nullable<double> cross_currency_rate { get; set; }
        public Nullable<int> must_email { get; set; }
        public Nullable<double> tax { get; set; }
        public string trmu_officer_processed_by_name { get; set; }
        public string prmo_submitter { get; set; }
        public string prmo_tl_submitter { get; set; }
        public string pay_officer_submitter { get; set; }
        public string pay_tl_submitter { get; set; }
        public string validation_officer_submitter { get; set; }
        public string validation_manager_submitter { get; set; }
        public string trm_officer_submitter { get; set; }
        public string trm_manager_submitter { get; set; }
        public string ccc_officer_submitter { get; set; }
        public string ccc_tl_submitter { get; set; }
        public string beneficiary { get; set; }
        public Nullable<int> commission_schedule { get; set; }
        public Nullable<int> cover_type { get; set; }
        public Nullable<double> facility_limit { get; set; }
        public Nullable<double> utilization_limit { get; set; }
        public Nullable<double> head_room_limit { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
    }
}
