//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class instruction_comments
    {
        public string instruction_comment { get; set; }
        public Nullable<System.DateTime> instruction_comment_date { get; set; }
        public Nullable<int> instruction_comment_by { get; set; }
        public long instruction_comment_id { get; set; }
        public Nullable<long> instruction_id { get; set; }
        public Nullable<long> instruction_comment_type_id { get; set; }
    }
}
