//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class instruction_type_allocations
    {
        public Nullable<long> instruction_type_id { get; set; }
        public Nullable<long> system_user_id { get; set; }
        public long instruction_type_allocation_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> inserted_date { get; set; }
        public Nullable<long> inserted_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<long> modified_by { get; set; }
    
        public virtual instructions_types instructions_types { get; set; }
        public virtual system_users system_users { get; set; }
    }
}
