//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class instructions_types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public instructions_types()
        {
            this.instruction_type_allocations = new HashSet<instruction_type_allocations>();
            this.instructions = new HashSet<instruction>();
        }
    
        public string instruction_type { get; set; }
        public long instruction_type_ID { get; set; }
        public string unit { get; set; }
        public string department { get; set; }
        public string instruction_code { get; set; }
        public string processing_department { get; set; }
        public Nullable<int> priority { get; set; }
        public string cutt_off_time { get; set; }
        public Nullable<int> processing_day { get; set; }
        public Nullable<int> allow_branch_to_process { get; set; }
        public Nullable<System.DateTime> last_escalation_email_sent_date { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<long> work_flow_id { get; set; }
        public Nullable<int> show_currency { get; set; }
        public Nullable<int> show_amount { get; set; }
        public Nullable<int> show_cross_currency { get; set; }
        public Nullable<int> allow_supporting_documents { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<instruction_type_allocations> instruction_type_allocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<instruction> instructions { get; set; }
    }
}
