//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class instructions_attachment
    {
        public string file_name { get; set; }
        public Nullable<System.DateTime> date_inserted { get; set; }
        public long attachment_id { get; set; }
        public Nullable<long> instruction_id { get; set; }
        public Nullable<long> inserted_by { get; set; }
        public Nullable<int> deleted { get; set; }
        public Nullable<long> deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_date { get; set; }
    }
}
