//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class instruction_submission
    {
        public Nullable<System.DateTime> instruction_submission_date { get; set; }
        public Nullable<int> instruction_submission_by { get; set; }
        public long instruction_submission_id { get; set; }
        public Nullable<long> instruction_id { get; set; }
        public Nullable<long> instruction_submission_user_type { get; set; }
        public Nullable<long> instruction_submission_status { get; set; }
        public Nullable<long> document_status_id { get; set; }
        public Nullable<int> is_return { get; set; }
    }
}
