//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class instructions_view2
    {
        public Nullable<double> amount { get; set; }
        public string comments { get; set; }
        public string reference { get; set; }
        public string file_name { get; set; }
        public long instruction_id { get; set; }
        public long instruction_type_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<long> client_id { get; set; }
        public string file_type { get; set; }
        public long Expr1 { get; set; }
        public string instruction_type { get; set; }
        public string Client_Name { get; set; }
        public string Client_Account_Number { get; set; }
        public string Client_Customer_Number { get; set; }
        public Nullable<System.DateTime> allocated_date { get; set; }
        public string processor_comments { get; set; }
        public string ftrob_comments { get; set; }
        public string ftroa_comments { get; set; }
        public string account_no { get; set; }
        public Nullable<int> currency_id { get; set; }
        public Nullable<System.DateTime> ftro_proccessed_date { get; set; }
        public Nullable<System.DateTime> ftro_approved_date { get; set; }
        public string branch_proccessed_date { get; set; }
        public Nullable<System.DateTime> processor_proccessed_date { get; set; }
        public Nullable<long> ftro_proccessed_by { get; set; }
        public Nullable<long> ftro_approved_by { get; set; }
        public Nullable<long> branch_proccessed_by { get; set; }
        public Nullable<long> processor_proccessed_by { get; set; }
        public string branch_user { get; set; }
        public string ftroa_user { get; set; }
        public string ftrob_user { get; set; }
        public string processor_user { get; set; }
        public Nullable<int> instruction_status { get; set; }
        public string document_status_name { get; set; }
        public Nullable<long> branch_approved_by { get; set; }
        public Nullable<long> system_user_id { get; set; }
        public string branch_approved_by_user { get; set; }
        public string branch_approved_date { get; set; }
        public Nullable<long> processor_approved_by { get; set; }
        public Nullable<System.DateTime> processor_approved_date { get; set; }
        public Nullable<long> document_status_id { get; set; }
        public string allocated_to_name { get; set; }
        public Nullable<long> allocated_to { get; set; }
        public string processor_approved_by_name { get; set; }
        public Nullable<long> locked_by { get; set; }
        public string locked_date { get; set; }
        public string locked_by_name { get; set; }
        public string currency_name { get; set; }
        public Nullable<int> inserted_by { get; set; }
        public string rm_comments { get; set; }
        public string ft_reference { get; set; }
        public Nullable<long> rm_id { get; set; }
        public Nullable<long> branch_id { get; set; }
        public Nullable<long> rm_proccessed_by { get; set; }
        public Nullable<System.DateTime> rm_proccessed_date { get; set; }
        public Nullable<System.DateTime> inserted_date { get; set; }
        public Nullable<System.DateTime> processor_allocated_date { get; set; }
        public Nullable<long> processor_allocated_by { get; set; }
        public Nullable<System.DateTime> ftro_allocated_date { get; set; }
        public Nullable<long> ftro_allocated_by { get; set; }
        public Nullable<int> exception { get; set; }
        public Nullable<int> foward_back_to_after_reversal { get; set; }
        public Nullable<long> branch_manual_approved_by { get; set; }
        public Nullable<System.DateTime> branch_manual_approved_date { get; set; }
        public string related_reference { get; set; }
        public Nullable<int> document_status_stage { get; set; }
    }
}
