//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class relationship_managers
    {
        public long RM_ID { get; set; }
        public string RM_Name { get; set; }
        public string AREA { get; set; }
        public string RM_Email { get; set; }
        public string R_Officer { get; set; }
        public string R_Officer_Email { get; set; }
        public string TB_Name { get; set; }
        public string TB_Email { get; set; }
        public Nullable<System.DateTime> Inserted_date { get; set; }
    }
}
