//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class search_by
    {
        public string search_by_name { get; set; }
        public string search_by_module { get; set; }
        public string search_by_value { get; set; }
        public int search_by_id { get; set; }
    }
}
