//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sub_menu()
        {
            this.report_rights = new HashSet<report_rights>();
            this.user_report_rights = new HashSet<user_report_rights>();
        }
    
        public int sub_menu_id { get; set; }
        public int menu_id { get; set; }
        public string sub_menu_name { get; set; }
        public string sub_menu_page { get; set; }
        public string sub_menu_checksum { get; set; }
        public string sub_menu_entity_types { get; set; }
    
        public virtual menu menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_rights> report_rights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_report_rights> user_report_rights { get; set; }
    }
}
