//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public system_users()
        {
            this.instruction_type_allocations = new HashSet<instruction_type_allocations>();
            this.user_team_leader = new HashSet<user_team_leader>();
        }
    
        public string system_user_login { get; set; }
        public Nullable<int> system_user_type { get; set; }
        public string system_user_password { get; set; }
        public string system_user_fname { get; set; }
        public Nullable<int> user_can_allocate_what_document_status { get; set; }
        public long system_user_id { get; set; }
        public string system_user_mname { get; set; }
        public string system_user_lname { get; set; }
        public string system_user_email { get; set; }
        public string system_user_id_number { get; set; }
        public Nullable<int> system_user_active { get; set; }
        public Nullable<int> system_user_failed_login_count { get; set; }
        public string system_user_mobile_number { get; set; }
        public string system_user_land_line { get; set; }
        public Nullable<int> change_password { get; set; }
        public string system_user_initials { get; set; }
        public Nullable<int> system_user_tittle { get; set; }
        public Nullable<int> system_user_branch { get; set; }
        public int system_tl_1 { get; set; }
        public string system_user_branch_code { get; set; }
        public Nullable<int> can_create { get; set; }
        public Nullable<int> can_submit { get; set; }
        public Nullable<int> is_team_leader { get; set; }
        public Nullable<int> system_manager { get; set; }
        public string check_sum { get; set; }
        public Nullable<int> system_user_status { get; set; }
        public Nullable<long> system_user_approved_by { get; set; }
        public Nullable<System.DateTime> system_user_approved_date { get; set; }
        public Nullable<long> system_user_modified_by { get; set; }
        public Nullable<System.DateTime> system_user_modified_date { get; set; }
        public Nullable<long> system_user_inserted_by { get; set; }
        public Nullable<System.DateTime> system_user_inserted_date { get; set; }
        public Nullable<int> system_header_view { get; set; }
        public Nullable<int> failed_login_count { get; set; }
        public Nullable<System.DateTime> change_password_date { get; set; }
        public string login_option { get; set; }
        public Nullable<int> can_process_instruction { get; set; }
        public Nullable<int> no_of_instructions_i_can_pack { get; set; }
        public Nullable<int> can_unpack_and_allocate { get; set; }
        public Nullable<int> can_modify_user_allocations { get; set; }
        public Nullable<int> ignore_checksum { get; set; }
        public Nullable<System.DateTime> last_successful_login { get; set; }
        public Nullable<int> total_work_allocated { get; set; }
        public Nullable<int> system_user_approval { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<instruction_type_allocations> instruction_type_allocations { get; set; }
        public virtual user_branch user_branch { get; set; }
        public virtual user_type_default user_type_default { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_team_leader> user_team_leader { get; set; }
    }
}
