//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_users_view
    {
        public string system_user_login { get; set; }
        public string names { get; set; }
        public string system_user_email { get; set; }
        public long system_user_id { get; set; }
        public Nullable<int> is_team_leader { get; set; }
        public int system_tl_1 { get; set; }
        public string teamleader { get; set; }
        public string user_type { get; set; }
        public Nullable<int> user_can_allocate_what_document_status { get; set; }
        public Nullable<int> system_user_type { get; set; }
        public Nullable<int> system_manager { get; set; }
        public string user_type_no { get; set; }
        public Nullable<int> system_user_branch { get; set; }
        public string branch_name { get; set; }
        public Nullable<int> system_user_failed_login_count { get; set; }
        public Nullable<int> failed_login_count { get; set; }
    }
}
