//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_type_default
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_type_default()
        {
            this.system_users = new HashSet<system_users>();
        }
    
        public string user_type { get; set; }
        public int user_type_id { get; set; }
        public string user_type_no { get; set; }
        public Nullable<int> is_team_leader { get; set; }
        public Nullable<double> minimum_amount { get; set; }
        public Nullable<double> maximum_amount { get; set; }
        public string user_type_queue { get; set; }
        public Nullable<int> display_user_type_queue { get; set; }
        public Nullable<int> popup_alert { get; set; }
        public Nullable<long> popup_alert_time { get; set; }
        public Nullable<int> can_change_priority { get; set; }
        public string unit { get; set; }
        public string stage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<system_users> system_users { get; set; }
    }
}
