//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Security_View
    {
        public string names { get; set; }
        public string system_user_login { get; set; }
        public string user_type { get; set; }
        public string branch_name { get; set; }
        public Nullable<int> system_user_active { get; set; }
    }
}
