//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_type
    {
        public int PkId { get; set; }
        public string user_type1 { get; set; }
        public Nullable<int> user_type_id { get; set; }
        public string user_type_no { get; set; }
        public Nullable<int> is_team_leader { get; set; }
        public Nullable<double> minimum_amount { get; set; }
        public Nullable<double> maximum_amount { get; set; }
        public string user_type_queue { get; set; }
        public Nullable<int> display_user_type_queue { get; set; }
        public Nullable<int> popup_alert { get; set; }
        public Nullable<long> popup_alert_time { get; set; }
        public Nullable<int> can_change_priority { get; set; }
        public string unit { get; set; }
        public string stage { get; set; }
        public Nullable<int> can_perform_callback { get; set; }
        public Nullable<int> can_perform_doc { get; set; }
        public Nullable<int> check_limit { get; set; }
        public Nullable<int> can_get_next { get; set; }
        public Nullable<int> can_add_attachment { get; set; }
        public Nullable<int> can_view_return_report { get; set; }
        public Nullable<int> can_insert_tax { get; set; }
        public Nullable<int> can_insert_core_banking_reference { get; set; }
        public Nullable<int> visible { get; set; }
    }
}
