//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_status
    {
        public int user_status1 { get; set; }
        public string user_status_desc { get; set; }
        public long user_status_id { get; set; }
        public Nullable<int> user_status_order { get; set; }
    }
}
