//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_load_report_paramaters
    {
        public Nullable<long> time_from { get; set; }
        public Nullable<long> time_to { get; set; }
        public long work_load_report_paramaters_id { get; set; }
        public string time_band { get; set; }
        public Nullable<int> time_band_order { get; set; }
    }
}
